// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoscowTrafficRestriction.InfrastructureServices.Gateways.Database;

namespace InformationAboutParks.WebService.Migrations
{
    [DbContext(typeof(TrafficRestrictionContext))]
    partial class TrafficRestrictionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("MoscowTrafficRestriction.DomainObjects.TrafficRestriction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventsExecuted")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventsNotExecutedInTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("INN")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuedPrescriptions")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOfManagingOrg")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolsComposed")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolsComposedForFailure")
                        .HasColumnType("TEXT");

                    b.Property<string>("SumOfFine")
                        .HasColumnType("TEXT");

                    b.Property<string>("ViolationsAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.Property<string>("global_id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrafficRestrictions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EventsExecuted = "0",
                            EventsNotExecutedInTime = "0",
                            INN = "7702560790",
                            IssuedPrescriptions = "1",
                            NameOfManagingOrg = "Товарищество собственников жилья «Рождественский бульвар дом 5-7 » 7702560790 2015",
                            ProtocolsComposed = "0",
                            ProtocolsComposedForFailure = "0",
                            SumOfFine = "0",
                            ViolationsAmount = "3",
                            Year = "2015",
                            global_id = "639913050"
                        },
                        new
                        {
                            Id = 2L,
                            EventsExecuted = "0",
                            EventsNotExecutedInTime = "0",
                            INN = "5074046552",
                            IssuedPrescriptions = "219",
                            NameOfManagingOrg = "ООО «Управляющая компания» Шишкин Лес» 5074046552 2015",
                            ProtocolsComposed = "60",
                            ProtocolsComposedForFailure = "1",
                            SumOfFine = "1998",
                            ViolationsAmount = "617",
                            Year = "2015",
                            global_id = "639913054"
                        },
                        new
                        {
                            Id = 3L,
                            EventsExecuted = "0",
                            EventsNotExecutedInTime = "0",
                            INN = "7737023041",
                            IssuedPrescriptions = "7",
                            NameOfManagingOrg = "Жилищно Строительный Кооператив «Фаза» 7737023041 2015",
                            ProtocolsComposed = "1",
                            ProtocolsComposedForFailure = "0",
                            SumOfFine = "40",
                            ViolationsAmount = "5",
                            Year = "2015",
                            global_id = "639913083"
                        },
                        new
                        {
                            Id = 4L,
                            EventsExecuted = "0",
                            EventsNotExecutedInTime = "0",
                            INN = "7712019533",
                            IssuedPrescriptions = "0",
                            NameOfManagingOrg = "ФГУП «Управление служебными и жилыми зданиями» РАМН 7712019533 2015",
                            ProtocolsComposed = "0",
                            ProtocolsComposedForFailure = "0",
                            SumOfFine = "0",
                            ViolationsAmount = "2",
                            Year = "2015",
                            global_id = "639913137"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
